### ISSUE TITLE
move `deps/` to package root

### ISSUE THREAD

**Issue by mattjj** [mattjj/pyhsmm#37]
Should `deps/` (namely Eigen) be moved from inside the `pyhsmm` subdirectory to the package root?

**Comment by yarden** [comment]
Yes, I can take care of this. I didn't do it before because I wasn't sure if ``deps/`` might be a place for Cython code dependency in future. If it's purely for external C/C++ libraries then it definitely shouldn't be a subdir of ``pyhsmm`` subdir because it's not part of the Python package. 

I'll also try to add travis support. I've been looking for an excuse to learn travis and now I have one.

**Comment by yarden** [comment]
This is now taken care of in: https://github.com/mattjj/pyhsmm/pull/39
