### ISSUE TITLE
HMM VLB

### ISSUE THREAD

**Issue by nfoti** [mattjj/pyhsmm#45]
It looks like the part of the variational lower-bound for HMMs is computed with the [line](https://github.com/mattjj/pyhsmm/blob/master/pyhsmm/internals/hmm_states.py#L483) `normalizer = np.logaddexp.reduce(alphal[0] + betal[0])`, but this doesn't seem right.  I think it should be something like `np.sum(np.logaddexp.reduce(alphal, axis=1))` which computes the normalization for the forward messages at each time and then combines them.  This corresponds to Eq. (3.74) in Ch. 3 of Beal's thesis.  Maybe I'm missing some cleverness though.

**Comment by mattjj** [comment]
I believe it's correct as it is: Eq. (3.60) in that thesis shows that Z is just the normalizer for the HMM MRF, which we can compute from combining the forwards and backwards the messages at any one index (like the code does using the first index). The \zeta defined Eq. (3.22) comprise an alternative way of writing the log normalizer in terms of filtering predictive probabilities (which turns out to be the most convenient way to compute the log normalizer for Gausisan LDS as far as I can tell!), but they're not the local potential normalizers from the two-way messages.

Actually something I realized (which isn't clear in Beal's thesis) is that this same thing happens for any conjugate mean field update to an exponential family factor, and this update to the HMM factor is just an instance of that phenomenon: right after the factor gets updated, its VLB term is just its log normalizer evaluated at its new variational natural parameters. Here are some symbols for an analogous (but not fully general) setup:

![latex-image-1](https://cloud.githubusercontent.com/assets/1458824/7668778/ab7e1a3e-fc18-11e4-8ce8-2873eef24f24.png)

(Apologies for any errors in that, which I typeset quickly, but I believe the general idea should be right!)

**Comment by nfoti** [comment]
Hmm, I'm getting different results using the current code vs. the proposed
in my version of the code (which is very close your yours).  I'll try to
get an example working with `pyhsmm` to try it out (very possible I have a
bug in mine somewhere).

Thanks.

**Comment by mattjj** [comment]
I admit I haven't tested mine thoroughly. It would be nice to write a VLB test with a comparison against [an exhaustive enumeration, like for the likelihood code](https://github.com/mattjj/pyhsmm/blob/bda20c23c4af7662db4c7ad1c95228b434ff3bad/tests/test_hmm_likelihood.py#L47-63).
