### ISSUE TITLE
Doubt: Observational distribution 

### ISSUE THREAD

**Issue by jmgo** [mattjj/pyhsmm#67]
Hi!

I want to use distribution with arbitrary shape for the observational distributions of a HMM. 
(arbitrary shape - referring to a distribution that does not have a particular function to describe it, but rather an array of probabilities for all possible values of the feature)

To do that can I use the Categorical distribution? Or is there some other way that is more appropriate?

Regards,
jmgoxx

**Comment by slinderman** [comment]
If your observations are discrete random variables, like

![image](https://cloud.githubusercontent.com/assets/5632040/17598222/717e0b46-5fc7-11e6-9420-c047e454b842.png)

then yes, you could model them with a categorical distribution with state-dependent probabilities. For example,

![image](https://cloud.githubusercontent.com/assets/5632040/17598253/9c7e76be-5fc7-11e6-828f-7480340b9170.png)

That is the standard way to handle such observations with an HMM, and the [Categorical](https://github.com/mattjj/pybasicbayes/blob/master/pybasicbayes/distributions/multinomial.py#L25) distribution would serve as the observation distribution. Does that answer your question?

**Comment by jmgo** [comment]
Hi!

Thank for the answer. 

Maybe this is a stupid question. Is there some way to deal with arbitrary continuous function? (I'm thinking that the closest is using a mixture of continuous functions)

Regards,
jmgoxx

**Comment by mattjj** [comment]
Yes, that makes sense; in fact, I'd say it'd be a CRF! I don't think we've worked with CRFs in pyhsmm, but it's a good idea to explore. You should be able to reuse the message passing routines in the `States` classes, and the strategy you're outlining should accomplish that. A lot of other things should work, though you may want to implement a `max_likelihood` or `resample` method to update the parameters of those classifiers (if indeed you want to fit them jointly with the rest of the model instead of just leaving them fixed).

Does that make sense? If it doesn't, and if you really want to pursue this using pyhsmm, I can say a bit more in detail.

**Comment by jmgo** [comment]
Thanks for the answer! 

Meanwhile, I implemented something similar to the example and it worked. I leave here the code if someone has the same issue:

```
import numpy as np
class ClassifierDist(object):

	def __init__(self, clf, state):
		self.clf   = clf
		self.state = state 

	def log_likelihood(self,x):
		prob = self.clf.predict_proba(x)[:,self.state]
		prob_log = np.log(prob)
		return prob_log 
```

I think that I will only need to optimize the parameters of the classifier first and then use those fixed parameters. If I need the optimize them jointly, I'll ask again.

Best Regards,
jmgoxx

**Comment by mattjj** [comment]
Glad to hear it, and thanks for the code. I'll close the issue for now, reopen or start a new one if you want to discuss further!
